etym/urls.py
from django.urls import path

from . import views

app_name = 'etym'
urlpatterns = [
    path('', views.index, name='index'),
    path('search', views.search, name='search'),
    path('search_json', views.search_json, name='search_json'),
]

pt_br_etym/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('etym/', include('etym.urls'))
]

etym/models.py
from django.db import models
from django_google_maps import fields as map_fields

class Region(models.Model):
    name = models.CharField(max_length=164)
    # latitude = models.FloatField(default=0)
    # longitude = models.FloatField(default=0)
    address = map_fields.AddressField(max_length=200)
    geolocation = map_fields.GeoLocationField(max_length=100)

    def __str__(self):
        return self.name

class Language(models.Model):
    name = models.CharField(max_length=164)

    def __str__(self):
        return self.name

class Origin(models.Model):
    word = models.CharField(max_length=164)
    meaning = models.CharField(max_length=164)

    def __str__(self):
        return self.word

class Modern(models.Model):
    modern_word = models.CharField(max_length=164)

    region = models.ForeignKey(Region, on_delete=models.CASCADE)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    origin = models.ForeignKey(Origin, on_delete=models.CASCADE)

    def __str__(self):
        return self.modern_word
    

etym/views.py
from django.shortcuts import render
from django.db.models import Q
from django.http import JsonResponse

from .models import Modern, Origin, Language, Region

def index(request):
    return render(request, 'etym/index.html')

def search_terms(search_term):
    return Modern.objects.filter(
        Q(modern_word__icontains=search_term) | 
        Q(region__name__icontains=search_term) | 
        Q(language__name__icontains=search_term) | 
        Q(origin__word__icontains=search_term)
    )

def search(request):
    search_term = request.GET.get('query', '')
    terms = search_terms(search_term)
    return render(request, 'etym/search.html', {'terms': terms})

def search_json(request):
    search_term = request.GET.get('query', '')
    terms = search_terms(search_term)

    regions = {}
    
    for term in terms:
        if term.region.name not in regions.keys():
            regions[term.region.name] = []

        related_words = []
        for word in term.region.modern_set.all():
            if word.modern_word != term.modern_word:
                related_words.append(word.modern_word)

        regions[term.region.name].append({
            'modern_word': term.modern_word,
            'related_words': related_words,
            'region': term.region.name,
            'language': term.language.name,
            'word': term.origin.word,
            'meaning': term.origin.meaning,
            'coordinates': { 
                'lat': term.region.geolocation.lat,
                'lng': term.region.geolocation.lon,
            },
        })

    return JsonResponse({'results': regions})
    

etym/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="{% static 'css/site.css' %}">
    <title>Etimologia: Português Brasileiro</title>
</head>
<body>
     <nav>
            <div class="navbar">
                <a href="">Dicionário Etimológico</a>
            </div>
            <div class="navbar">
                <a href="">Sobre o projeto</a>
                <a href="">Entrar em contato</a>
            </div>   
    </nav>
    <main>
    {% block content %}
    {% endblock content %}
    </main>
</body>
</html>

etym/templates/etym/index.html
{% extends "base.html" %}

{% block content %}
    <div class="search-container">
        <form method="GET" action="{% url 'etym:search' %}">
            <input name="query" placeholder="Confira aqui...">
            <button>Buscar</button>
        </form>
    </div>
{% endblock content %}
    

etym/templates/etym/search.html
{% extends "base.html" %}

{% block content %}
    <div class="search-results">
        <div class="terms">
            {% for term in terms %}
                <div class="term">
                    {{ term.modern_word }} 
                    | da língua: {{ term.language.name }} 
                    | da palavra: 
                    <em>{{ term.origin.word }}</em>  
                    que significa "{{ term.origin.meaning }}"
                </div>
            {% endfor %}
        </div>
        <div id="map"></div>
    </div>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/axios/0.18.0/axios.min.js"></script>
    <script>
      function generateInfo(words) {
        // const words = term.related_words.map((word) => {
        //   return `<div>${word}</div>`
        // })
        // return `${term.modern_word}<br /><h4>Palavras relacionadas:</h4>${words.join('')}`

        const terms = words.map((word) => {
          return `<div>${word.modern_word}</div>`
        }).join('');

        let relatedTerms = [];
        let existingWords = words.map((word) => word.modern_word);

        // words.forEach((word) => {
        //   relatedTerms[word.modern_word] = null;
        //   word.related_words.forEach((relatedWord) => {
        //     if(existingWords.indexOf(relatedWord) !== -1) {
        //       relatedTerms.push(relatedWord)
        //     }
        //   });
        // });

        // // console.log(relatedTerms)
        // relatedTerms = relatedTerms.map((word) => {
        //   return `<div><em>${word}</em></div>`;
        // }).join('');
        
        return terms;
      }
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: 5, lng: -3},
          zoom: 3
        });

        const url = '/etym/search_json?' + window.location.href.split('?')[1]
        console.log(url)
        axios.get(url)
        .then((response) => {
          const regions = response.data.results;

          Object.keys(regions).forEach((region) => {
            const info = new google.maps.InfoWindow({
              content: generateInfo(regions[region])
            })

            const marker = new google.maps.Marker({
              position: regions[region][0].coordinates,
              map: map,
              title: region
            })
            marker.addListener('click', function() {
              info.open(map, marker);
            });
          })

          // response.data.results.map((term) => {
          //   var infowindow = new google.maps.InfoWindow({
          //     content: generateInfo(term)
          //   });

          //   var marker = new google.maps.Marker({
          //     position: term.coordinates,
          //     map: map,
          //     title: term.modern_word
          //   });
          //   marker.addListener('click', function() {
          //     infowindow.open(map, marker);
          //   });
          // })
          
        })
      }
    </script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBXxyhOKpXtddGPCnI6neLG_gnoLdVHbZk&callback=initMap"
    async defer></script>
{% endblock content %}  